[Distribution]
Architecture=arm64

[Build]
CacheDirectory=mkosi.cache
#ToolsTree=default

[Output]
Format=tar
Output=image

[Content]
Bootable=no
UnifiedKernelImages=no
KernelModulesInitrd=no
KernelCommandLine=clk_ignore_unused pd_ignore_unused audit=0 root=PARTLABEL=rootfs rootwait deferred_probe_timeout=60
RootPassword=14
Hostname=qcom

PackageDirectories=mkosi.packages
