[Match]
Distribution=debian

[Distribution]
Release=sid
Repositories=main,contrib,non-free-firmware

[Content]
Packages=
	alsa-utils
	apt-utils
	btop
	e2fsprogs
	ethtool
	firmware-atheros
	firmware-linux-free
	firmware-linux-nonfree
	firmware-qcom-soc
	gdisk
	kmod
	iproute2
	less
	libdrm-freedreno1
	libdrm-tests
	libdrm2
#	linux-image-arm64
	locales
	login
	mc
	network-manager
	pciutils
	plocate
	qrtr-tools
	rmtfs
	systemd-boot
	systemd-boot-efi
	systemd-repart
	systemd-timesyncd
	tcpdump
#	task-gnome-desktop
	tqftpserv
	tzdata
	usbutils
	vim
	wpasupplicant
